[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bootcamp_data"
version = "0.1.0"
dependencies = [
    "pandas",
    "pyarrow",
]

[tool.setuptools.packages.find]
where = ["src"]